spring:
  application:
    name: admin-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: testsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecret
services:
  auth-url: http://localhost:8081
  job-url: http://localhost:8082
  application-url: http://localhost:8083

eureka:
  client:
    enabled: false

jwt:
  secret: testsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecret
