spring:
  application:
    name: application-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: testsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecret

eureka:
  client:
    enabled: false

jwt:
  secret: testsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecret
